# -*- coding: utf-8 -*-
"""
Created on Sun Jul 12 16:16:19 2026

@author: Ajay R. Dwivedi
"""


"""
Structural summary analysis for generic metal-ion polymer electrolytes.

Reads the master coordination databases generated by:

    01_build_master_coordination_database.py

Produces:
    1. Block-averaged structural metrics
    2. Overall structural summary
    3. Coordination-state populations
    4. Coordination-number distributions
    5. Joint PEO-TFSI coordination distributions
    6. TFSI denticity distributions
    7. PEO-chain-sharing and bridging distributions
    8. Metal-TFSI cluster-size distributions
    9. Manuscript-ready plots

Author: Ajay Dwivedi
"""

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# ============================================================
# USER SETTINGS
# ============================================================

SYSTEMS = {
    "example_system": {
        "metal": "metal",
        "composition": "composition",
        "master_file": "coordination_database/example_system/master_coordination_example_system.csv.gz",
        "frame_file": "coordination_database/example_system/frame_summary_example_system.csv",
        "tfsi_bridging_file": "coordination_database/example_system/tfsi_bridging_example_system.csv.gz",
        "peo_bridging_file": "coordination_database/example_system/peo_chain_bridging_example_system.csv.gz",
        "cluster_file": "coordination_database/example_system/cluster_summary_example_system.csv.gz",
    },
}


# Order in which compositions appear in plots.
#
# Replace these labels with your actual four compositions.
COMPOSITION_ORDER = [
    "20_5",
    "10_10",
    "5_15",
    "5_20",
]

# Number of trajectory blocks used for uncertainty estimates.
N_BLOCKS = 5

OUTPUT_DIR = Path("structural_summary")

# Plot settings.
FIGURE_DPI = 300
SAVE_PDF = True

# Remove an initial trajectory portion if needed.
#
# Set to 0.0 to use the complete analyzed trajectory.
DISCARD_INITIAL_FRACTION = 0.0


# ============================================================
# COLUMN TYPES
# ============================================================

MASTER_STRING_COLUMNS = [
    "peo_oxygen_atom_ids",
    "peo_chain_resids",
    "peo_local_eo_indices",
    "peo_chain_eo_mapping",
    "tfsi_oxygen_atom_ids",
    "tfsi_resids",
    "tfsi_denticity",
    "bridging_tfsi_resids",
    "shared_peo_chain_resids",
    "local_peo_bridge_chain_resids",
    "remote_peo_shared_chain_resids",
    "cluster_id",
]


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def ensure_file_exists(path_string):
    """Raise a clear error if an input file is missing."""

    path = Path(path_string)

    if not path.exists():
        raise FileNotFoundError(
            f"Required input file not found:\n{path.resolve()}"
        )

    return path


def read_master_database(path_string):
    """Read the master database without mixed-type warnings."""

    path = ensure_file_exists(path_string)

    dtype_map = {
        column: "string"
        for column in MASTER_STRING_COLUMNS
    }

    return pd.read_csv(
        path,
        dtype=dtype_map,
        low_memory=False,
    )


def read_table(path_string):
    """Read a CSV or compressed CSV."""

    path = ensure_file_exists(path_string)

    return pd.read_csv(
        path,
        low_memory=False,
    )


def discard_initial_frames(dataframe, fraction):
    """
    Remove an initial fraction of frames.

    The cutoff is based on unique frame numbers.
    """

    if fraction <= 0:
        return dataframe.copy()

    if fraction >= 1:
        raise ValueError(
            "DISCARD_INITIAL_FRACTION must be less than 1."
        )

    unique_frames = np.sort(
        dataframe["frame"].unique()
    )

    n_discard = int(
        np.floor(
            len(unique_frames) * fraction
        )
    )

    retained_frames = set(
        unique_frames[n_discard:]
    )

    return dataframe[
        dataframe["frame"].isin(retained_frames)
    ].copy()


def assign_frame_blocks(dataframe, n_blocks):
    """
    Assign unique trajectory frames to approximately equal blocks.

    This avoids splitting rows from the same frame across blocks.
    """

    result = dataframe.copy()

    unique_frames = np.sort(
        result["frame"].unique()
    )

    if len(unique_frames) < n_blocks:
        raise ValueError(
            f"Only {len(unique_frames)} frames are available, "
            f"but N_BLOCKS={n_blocks}."
        )

    frame_groups = np.array_split(
        unique_frames,
        n_blocks,
    )

    frame_to_block = {}

    for block_index, frame_group in enumerate(
        frame_groups,
        start=1,
    ):
        for frame in frame_group:
            frame_to_block[int(frame)] = block_index

    result["block"] = (
        result["frame"]
        .map(frame_to_block)
        .astype(int)
    )

    return result


def block_statistics(block_table, value_columns):
    """
    Calculate mean, standard deviation, and standard error
    across block averages.
    """

    rows = []

    for column in value_columns:
        values = (
            block_table[column]
            .dropna()
            .astype(float)
        )

        n = len(values)

        mean_value = values.mean()

        std_value = (
            values.std(ddof=1)
            if n > 1
            else np.nan
        )

        sem_value = (
            std_value / np.sqrt(n)
            if n > 1
            else np.nan
        )

        rows.append({
            "metric": column,
            "mean": mean_value,
            "block_std": std_value,
            "block_sem": sem_value,
            "n_blocks": n,
        })

    return pd.DataFrame(rows)


def parse_denticity_json(value):
    """
    Parse a tfsi_denticity JSON entry.

    Example:
        '{"41":1,"43":2}'
    becomes:
        [1, 2]
    """

    if pd.isna(value):
        return []

    text = str(value).strip()

    if text in ("", "{}", "<NA>"):
        return []

    try:
        mapping = json.loads(text)
    except json.JSONDecodeError:
        return []

    return [
        int(denticity)
        for denticity in mapping.values()
    ]


def safe_probability_table(series, value_name):
    """Return count and probability for a categorical variable."""

    counts = (
        series
        .value_counts(dropna=False)
        .sort_index()
    )

    total = counts.sum()

    table = counts.rename("count").reset_index()

    table.columns = [
        value_name,
        "count",
    ]

    table["probability"] = (
        table["count"] / total
        if total > 0
        else 0.0
    )

    return table


def save_figure(fig, filename_stem):
    """Save a figure as PNG and optionally PDF."""

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    fig.savefig(
        OUTPUT_DIR / f"{filename_stem}.png",
        dpi=FIGURE_DPI,
        bbox_inches="tight",
    )

    if SAVE_PDF:
        fig.savefig(
            OUTPUT_DIR / f"{filename_stem}.pdf",
            bbox_inches="tight",
        )

    plt.close(fig)


def sort_compositions(dataframe):
    """Apply a consistent composition order."""

    result = dataframe.copy()

    known_order = [
        value
        for value in COMPOSITION_ORDER
        if value in result["composition"].unique()
    ]

    remaining = [
        value
        for value in result["composition"].unique()
        if value not in known_order
    ]

    complete_order = known_order + sorted(remaining)

    result["composition"] = pd.Categorical(
        result["composition"],
        categories=complete_order,
        ordered=True,
    )

    return result.sort_values(
        ["metal_species", "composition"]
    )


# ============================================================
# SYSTEM-LEVEL ANALYSIS
# ============================================================

def analyze_system(system_name, config):
    """Analyze one master structural database."""

    print("\n" + "=" * 78)
    print(f"Analyzing structural database: {system_name}")
    print("=" * 78)

    master = read_master_database(
        config["master_file"]
    )

    frames = read_table(
        config["frame_file"]
    )

    tfsi_bridging = read_table(
        config["tfsi_bridging_file"]
    )

    peo_bridging = read_table(
        config["peo_bridging_file"]
    )

    clusters = read_table(
        config["cluster_file"]
    )

    master = discard_initial_frames(
        master,
        DISCARD_INITIAL_FRACTION,
    )

    frames = discard_initial_frames(
        frames,
        DISCARD_INITIAL_FRACTION,
    )

    tfsi_bridging = discard_initial_frames(
        tfsi_bridging,
        DISCARD_INITIAL_FRACTION,
    )

    peo_bridging = discard_initial_frames(
        peo_bridging,
        DISCARD_INITIAL_FRACTION,
    )

    clusters = discard_initial_frames(
        clusters,
        DISCARD_INITIAL_FRACTION,
    )

    master = assign_frame_blocks(
        master,
        N_BLOCKS,
    )

    frames = assign_frame_blocks(
        frames,
        N_BLOCKS,
    )

    tfsi_bridging = assign_frame_blocks(
        tfsi_bridging,
        N_BLOCKS,
    )

    peo_bridging = assign_frame_blocks(
        peo_bridging,
        N_BLOCKS,
    )

    clusters = assign_frame_blocks(
        clusters,
        N_BLOCKS,
    )

    metal = config["metal"]
    composition = config["composition"]

    system_output_dir = OUTPUT_DIR / system_name

    system_output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ========================================================
    # 1. FRAME-LEVEL BLOCK AVERAGES
    # ========================================================

    structural_columns = [
        "frac_P",
        "frac_PT",
        "frac_T",
        "frac_F",

        "mean_peo_oxygen_cn",
        "mean_peo_chain_cn",
        "mean_tfsi_oxygen_cn",
        "mean_tfsi_molecular_cn",
        "mean_total_oxygen_cn",

        "fraction_coordinated_tfsi_bridging",
        "fraction_all_tfsi_bridging",
        "fraction_metals_tfsi_bridged",

        "fraction_coordinating_peo_chains_shared",
        "fraction_all_peo_chains_shared",
        "fraction_coordinating_peo_chains_local_bridging",
        "fraction_all_peo_chains_local_bridging",

        "fraction_metals_shared_peo_chain",
        "fraction_metals_local_peo_bridged",
        "fraction_metals_remote_peo_shared",

        "mean_metals_per_coordinating_peo_chain",
        "max_metals_on_one_peo_chain",

        "fraction_metals_any_bridge",
        "fraction_metals_both_peo_tfsi_bridged",
        "fraction_metals_peo_only_bridged",
        "fraction_metals_tfsi_only_bridged",

        "mean_cluster_metals_number_average",
        "mean_cluster_metals_weight_average",
        "largest_cluster_n_metals",
        "largest_cluster_metal_fraction",
        "fraction_metals_in_multi_metal_clusters",
        "fraction_single_metal_clusters",
    ]

    available_structural_columns = [
        column
        for column in structural_columns
        if column in frames.columns
    ]

    missing_columns = sorted(
        set(structural_columns)
        - set(available_structural_columns)
    )

    if missing_columns:
        print(
            "\nWarning: the following frame-summary columns "
            "were not found:"
        )

        for column in missing_columns:
            print(f"  - {column}")

    block_frame_means = (
        frames
        .groupby("block", as_index=False)[
            available_structural_columns
        ]
        .mean()
    )

    block_frame_means.insert(
        0,
        "composition",
        composition,
    )

    block_frame_means.insert(
        0,
        "metal_species",
        metal,
    )

    block_frame_means.insert(
        0,
        "system",
        system_name,
    )

    block_frame_means.to_csv(
        system_output_dir
        / f"block_means_{system_name}.csv",
        index=False,
    )

    overall_summary = block_statistics(
        block_frame_means,
        available_structural_columns,
    )

    overall_summary.insert(
        0,
        "composition",
        composition,
    )

    overall_summary.insert(
        0,
        "metal_species",
        metal,
    )

    overall_summary.insert(
        0,
        "system",
        system_name,
    )

    overall_summary.to_csv(
        system_output_dir
        / f"overall_summary_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 2. COORDINATION STATE POPULATIONS
    # ========================================================

    state_order = [
        "P",
        "PT",
        "T",
        "F",
    ]

    state_block = (
        master
        .groupby(
            ["block", "coordination_state"]
        )
        .size()
        .rename("count")
        .reset_index()
    )

    state_totals = (
        state_block
        .groupby("block")["count"]
        .transform("sum")
    )

    state_block["fraction"] = (
        state_block["count"]
        / state_totals
    )

    state_block = (
        state_block
        .pivot(
            index="block",
            columns="coordination_state",
            values="fraction",
        )
        .fillna(0.0)
        .reindex(
            columns=state_order,
            fill_value=0.0,
        )
        .reset_index()
    )

    state_block.insert(
        0,
        "composition",
        composition,
    )

    state_block.insert(
        0,
        "metal_species",
        metal,
    )

    state_block.insert(
        0,
        "system",
        system_name,
    )

    state_block.to_csv(
        system_output_dir
        / f"state_block_fractions_{system_name}.csv",
        index=False,
    )

    state_summary_rows = []

    for state in state_order:
        values = state_block[state]

        state_summary_rows.append({
            "system": system_name,
            "metal_species": metal,
            "composition": composition,
            "state": state,
            "mean_fraction": values.mean(),
            "block_std": values.std(ddof=1),
            "block_sem": (
                values.std(ddof=1)
                / np.sqrt(len(values))
            ),
        })

    state_summary = pd.DataFrame(
        state_summary_rows
    )

    state_summary.to_csv(
        system_output_dir
        / f"state_summary_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 3. COORDINATION-NUMBER DISTRIBUTIONS
    # ========================================================

    coordination_columns = [
        "n_peo_oxygen",
        "n_peo_chains",
        "n_tfsi_oxygen",
        "n_tfsi_molecules",
        "total_oxygen_cn",
    ]

    coordination_distributions = []

    for column in coordination_columns:

        table = safe_probability_table(
            master[column],
            "coordination_number",
        )

        table.insert(
            0,
            "metric",
            column,
        )

        table.insert(
            0,
            "composition",
            composition,
        )

        table.insert(
            0,
            "metal_species",
            metal,
        )

        table.insert(
            0,
            "system",
            system_name,
        )

        coordination_distributions.append(
            table
        )

    coordination_distribution = pd.concat(
        coordination_distributions,
        ignore_index=True,
    )

    coordination_distribution.to_csv(
        system_output_dir
        / f"coordination_distributions_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 4. JOINT PEO-TFSI COORDINATION MAP
    # ========================================================

    joint_counts = (
        master
        .groupby(
            [
                "n_peo_oxygen",
                "n_tfsi_molecules",
            ]
        )
        .size()
        .rename("count")
        .reset_index()
    )

    joint_counts["probability"] = (
        joint_counts["count"]
        / joint_counts["count"].sum()
    )

    joint_counts.insert(
        0,
        "composition",
        composition,
    )

    joint_counts.insert(
        0,
        "metal_species",
        metal,
    )

    joint_counts.insert(
        0,
        "system",
        system_name,
    )

    joint_counts.to_csv(
        system_output_dir
        / f"joint_peo_tfsi_coordination_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 5. TFSI DENTICITY DISTRIBUTION
    # ========================================================

    denticity_values = []

    for value in master["tfsi_denticity"]:
        denticity_values.extend(
            parse_denticity_json(value)
        )

    if denticity_values:
        denticity_distribution = (
            safe_probability_table(
                pd.Series(denticity_values),
                "denticity",
            )
        )
    else:
        denticity_distribution = pd.DataFrame(
            columns=[
                "denticity",
                "count",
                "probability",
            ]
        )

    denticity_distribution.insert(
        0,
        "composition",
        composition,
    )

    denticity_distribution.insert(
        0,
        "metal_species",
        metal,
    )

    denticity_distribution.insert(
        0,
        "system",
        system_name,
    )

    denticity_distribution.to_csv(
        system_output_dir
        / f"tfsi_denticity_distribution_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 6. TFSI BRIDGING DISTRIBUTION
    # ========================================================

    tfsi_metal_count_distribution = (
        safe_probability_table(
            tfsi_bridging["n_coordinating_metals"],
            "n_coordinating_metals",
        )
    )

    tfsi_metal_count_distribution.insert(
        0,
        "composition",
        composition,
    )

    tfsi_metal_count_distribution.insert(
        0,
        "metal_species",
        metal,
    )

    tfsi_metal_count_distribution.insert(
        0,
        "system",
        system_name,
    )

    tfsi_metal_count_distribution.to_csv(
        system_output_dir
        / f"tfsi_metals_per_anion_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 7. PEO CHAIN OCCUPANCY AND BRIDGING
    # ========================================================

    peo_metals_per_chain_distribution = (
        safe_probability_table(
            peo_bridging["n_coordinating_metals"],
            "n_coordinating_metals",
        )
    )

    peo_metals_per_chain_distribution.insert(
        0,
        "composition",
        composition,
    )

    peo_metals_per_chain_distribution.insert(
        0,
        "metal_species",
        metal,
    )

    peo_metals_per_chain_distribution.insert(
        0,
        "system",
        system_name,
    )

    peo_metals_per_chain_distribution.to_csv(
        system_output_dir
        / f"peo_metals_per_chain_{system_name}.csv",
        index=False,
    )

    shared_peo_pairs = peo_bridging[
        peo_bridging["n_metal_pairs"] > 0
    ].copy()

    if len(shared_peo_pairs) > 0:

        separation_distribution = (
            shared_peo_pairs[
                "minimum_pair_eo_separation"
            ]
            .dropna()
            .astype(int)
        )

        separation_distribution = (
            safe_probability_table(
                separation_distribution,
                "minimum_eo_separation",
            )
        )

    else:
        separation_distribution = pd.DataFrame(
            columns=[
                "minimum_eo_separation",
                "count",
                "probability",
            ]
        )

    separation_distribution.insert(
        0,
        "composition",
        composition,
    )

    separation_distribution.insert(
        0,
        "metal_species",
        metal,
    )

    separation_distribution.insert(
        0,
        "system",
        system_name,
    )

    separation_distribution.to_csv(
        system_output_dir
        / f"peo_minimum_eo_separation_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 8. CLUSTER-SIZE DISTRIBUTIONS
    # ========================================================

    cluster_number_distribution = (
        clusters
        .groupby("n_metals")
        .size()
        .rename("cluster_count")
        .reset_index()
        .sort_values("n_metals")
    )

    cluster_number_distribution[
        "cluster_probability"
    ] = (
        cluster_number_distribution["cluster_count"]
        / cluster_number_distribution[
            "cluster_count"
        ].sum()
    )

    cluster_number_distribution[
        "metal_weight"
    ] = (
        cluster_number_distribution["n_metals"]
        * cluster_number_distribution["cluster_count"]
    )

    cluster_number_distribution[
        "metal_fraction"
    ] = (        cluster_number_distribution["metal_weight"]
        / cluster_number_distribution[
            "metal_weight"
        ].sum()
    )

    cluster_number_distribution.insert(
        0,
        "composition",
        composition,
    )

    cluster_number_distribution.insert(
        0,
        "metal_species",
        metal,
    )

    cluster_number_distribution.insert(
        0,
        "system",
        system_name,
    )

    cluster_number_distribution.to_csv(
        system_output_dir
        / f"cluster_size_distribution_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 9. BASIC SYSTEM FIGURES
    # ========================================================

    make_system_coordination_plot(
        system_name,
        metal,
        composition,
        coordination_distribution,
    )

    make_system_joint_map(
        system_name,
        metal,
        composition,
        joint_counts,
    )

    make_system_denticity_plot(
        system_name,
        metal,
        composition,
        denticity_distribution,
    )

    make_system_cluster_plot(
        system_name,
        metal,
        composition,
        cluster_number_distribution,
    )

    print(
        f"Completed structural summary for {system_name}."
    )

    return {
        "overall_summary": overall_summary,
        "state_summary": state_summary,
        "coordination_distribution":
            coordination_distribution,
        "joint_coordination": joint_counts,
        "denticity_distribution":
            denticity_distribution,
        "tfsi_metals_per_anion":
            tfsi_metal_count_distribution,
        "peo_metals_per_chain":
            peo_metals_per_chain_distribution,
        "peo_eo_separation":
            separation_distribution,
        "cluster_distribution":
            cluster_number_distribution,
        "block_means":
            block_frame_means,
    }


# ============================================================
# SYSTEM-LEVEL PLOTS
# ============================================================

def make_system_coordination_plot(
    system_name,
    metal,
    composition,
    coordination_distribution,
):
    """Plot selected coordination-number distributions."""

    metrics = [
        (
            "n_peo_oxygen",
            "PEO oxygen coordination number",
        ),
        (
            "n_tfsi_molecules",
            "Distinct TFSI molecules per metal",
        ),
        (
            "total_oxygen_cn",
            "Total oxygen coordination number",
        ),
    ]

    for metric, xlabel in metrics:

        subset = coordination_distribution[
            coordination_distribution["metric"]
            == metric
        ]

        fig, ax = plt.subplots(
            figsize=(6.2, 4.5)
        )

        ax.plot(
            subset["coordination_number"],
            subset["probability"],
            marker="o",
        )

        ax.set_xlabel(xlabel)
        ax.set_ylabel("Probability")
        ax.set_title(
            f"{metal}, composition {composition}"
        )

        ax.set_ylim(bottom=0)
        ax.grid(alpha=0.25)

        fig.tight_layout()

        save_figure(
            fig,
            f"{system_name}_{metric}_distribution",
        )


def make_system_joint_map(
    system_name,
    metal,
    composition,
    joint_counts,
):
    """Plot joint PEO oxygen CN versus TFSI molecular CN."""

    pivot = (
        joint_counts
        .pivot(
            index="n_tfsi_molecules",
            columns="n_peo_oxygen",
            values="probability",
        )
        .fillna(0.0)
        .sort_index()
        .sort_index(axis=1)
    )

    fig, ax = plt.subplots(
        figsize=(7.0, 5.2)
    )

    image = ax.imshow(
        pivot.values,
        origin="lower",
        aspect="auto",
        interpolation="nearest",
    )

    ax.set_xticks(
        np.arange(len(pivot.columns))
    )

    ax.set_xticklabels(
        pivot.columns.astype(int)
    )

    ax.set_yticks(
        np.arange(len(pivot.index))
    )

    ax.set_yticklabels(
        pivot.index.astype(int)
    )

    ax.set_xlabel(
        "Number of coordinating PEO oxygens"
    )

    ax.set_ylabel(
        "Number of coordinating TFSI molecules"
    )

    ax.set_title(
        f"{metal}, composition {composition}"
    )

    colorbar = fig.colorbar(
        image,
        ax=ax,
    )

    colorbar.set_label(
        "Probability"
    )

    fig.tight_layout()

    save_figure(
        fig,
        f"{system_name}_joint_peo_tfsi_map",
    )


def make_system_denticity_plot(
    system_name,
    metal,
    composition,
    denticity_distribution,
):
    """Plot TFSI denticity distribution."""

    if denticity_distribution.empty:
        return

    fig, ax = plt.subplots(
        figsize=(5.8, 4.4)
    )

    ax.bar(
        denticity_distribution["denticity"],
        denticity_distribution["probability"],
    )

    ax.set_xlabel(
        "TFSI denticity"
    )

    ax.set_ylabel(
        "Probability among coordinated TFSI"
    )

    ax.set_title(
        f"{metal}, composition {composition}"
    )

    ax.set_xticks(
        denticity_distribution[
            "denticity"
        ].astype(int)
    )

    ax.set_ylim(bottom=0)
    ax.grid(
        axis="y",
        alpha=0.25,
    )

    fig.tight_layout()

    save_figure(
        fig,
        f"{system_name}_tfsi_denticity",
    )


def make_system_cluster_plot(
    system_name,
    metal,
    composition,
    cluster_distribution,
):
    """Plot metal-weighted cluster-size distribution."""

    fig, ax = plt.subplots(
        figsize=(6.0, 4.5)
    )

    ax.bar(
        cluster_distribution["n_metals"],
        cluster_distribution["metal_fraction"],
    )

    ax.set_xlabel(
        "Number of metal ions in cluster"
    )

    ax.set_ylabel(
        "Fraction of metal ions"
    )

    ax.set_title(
        f"{metal}, composition {composition}"
    )

    ax.set_xticks(
        cluster_distribution[
            "n_metals"
        ].astype(int)
    )

    ax.set_ylim(bottom=0)
    ax.grid(
        axis="y",
        alpha=0.25,
    )

    fig.tight_layout()

    save_figure(
        fig,
        f"{system_name}_cluster_size_distribution",
    )


# ============================================================
# COMBINED COMPARISON TABLES AND PLOTS
# ============================================================

def make_combined_metric_plot(
    summary_table,
    metric,
    ylabel,
    filename,
):
    """Plot a block-averaged structural metric for all systems."""

    subset = summary_table[
        summary_table["metric"] == metric
    ].copy()

    if subset.empty:
        print(
            f"Skipping missing combined metric: {metric}"
        )
        return

    subset = sort_compositions(subset)

    fig, ax = plt.subplots(
        figsize=(7.2, 5.0)
    )

    for metal, metal_data in subset.groupby(
        "metal_species",
        observed=True,
    ):

        metal_data = metal_data.sort_values(
            "composition"
        )

        x = np.arange(
            len(metal_data)
        )

        ax.errorbar(
            x,
            metal_data["mean"],
            yerr=metal_data["block_std"],
            marker="o",
            capsize=4,
            label=metal,
        )

        ax.set_xticks(x)

        ax.set_xticklabels(
            metal_data["composition"].astype(str)
        )

    ax.set_xlabel(
        "IL:salt composition"
    )

    ax.set_ylabel(ylabel)

    ax.legend(
        frameon=False
    )

    ax.grid(
        axis="y",
        alpha=0.25,
    )

    fig.tight_layout()

    save_figure(
        fig,
        filename,
    )


def make_combined_state_plot(state_summary):
    """Plot P/PT/T/F state populations across systems."""

    data = sort_compositions(
        state_summary
    )

    systems = (
        data[
            [
                "metal_species",
                "composition",
            ]
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    labels = [
        f"{row.metal_species}\n{row.composition}"
        for row in systems.itertuples()
    ]

    x = np.arange(
        len(systems)
    )

    state_order = [
        "P",
        "PT",
        "T",
        "F",
    ]

    bottom = np.zeros(
        len(systems)
    )

    fig, ax = plt.subplots(
        figsize=(9.0, 5.3)
    )

    for state in state_order:

        heights = []

        for row in systems.itertuples():

            selection = data[
                (data["metal_species"]
                 == row.metal_species)
                &
                (data["composition"]
                 == row.composition)
                &
                (data["state"] == state)
            ]

            if selection.empty:
                heights.append(0.0)
            else:
                heights.append(
                    selection[
                        "mean_fraction"
                    ].iloc[0]
                )

        heights = np.asarray(
            heights
        )

        ax.bar(
            x,
            heights,
            bottom=bottom,
            label=state,
        )

        bottom += heights

    ax.set_xticks(x)
    ax.set_xticklabels(labels)

    ax.set_ylabel(
        "Coordination-state fraction"
    )

    ax.set_ylim(
        0,
        1,
    )

    ax.legend(
        frameon=False,
        ncol=4,
    )

    ax.grid(
        axis="y",
        alpha=0.25,
    )

    fig.tight_layout()

    save_figure(
        fig,
        "combined_coordination_state_fractions",
    )


# ============================================================
# MAIN DRIVER
# ============================================================

def main():

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("=" * 78)
    print("STRUCTURAL SUMMARY AND DISTRIBUTIONS")
    print("=" * 78)

    results = {}

    for system_name, config in SYSTEMS.items():
        results[system_name] = analyze_system(
            system_name,
            config,
        )

    # --------------------------------------------------------
    # Combine all tables
    # --------------------------------------------------------

    combined_overall_summary = pd.concat(
        [
            result["overall_summary"]
            for result in results.values()
        ],
        ignore_index=True,
    )

    combined_state_summary = pd.concat(
        [
            result["state_summary"]
            for result in results.values()
        ],
        ignore_index=True,
    )

    combined_coordination_distribution = pd.concat(
        [
            result["coordination_distribution"]
            for result in results.values()
        ],
        ignore_index=True,
    )

    combined_joint_coordination = pd.concat(
        [
            result["joint_coordination"]
            for result in results.values()
        ],
        ignore_index=True,
    )

    combined_denticity = pd.concat(
        [
            result["denticity_distribution"]
            for result in results.values()
        ],
        ignore_index=True,
    )

    combined_tfsi_bridging = pd.concat(
        [
            result["tfsi_metals_per_anion"]
            for result in results.values()
        ],
        ignore_index=True,
    )

    combined_peo_occupancy = pd.concat(
        [
            result["peo_metals_per_chain"]
            for result in results.values()
        ],
        ignore_index=True,
    )

    combined_peo_separation = pd.concat(
        [
            result["peo_eo_separation"]
            for result in results.values()
        ],
        ignore_index=True,
    )

    combined_cluster_distribution = pd.concat(
        [
            result["cluster_distribution"]
            for result in results.values()
        ],
        ignore_index=True,
    )

    combined_block_means = pd.concat(
        [
            result["block_means"]
            for result in results.values()
        ],
        ignore_index=True,
    )

    # --------------------------------------------------------
    # Save combined tables
    # --------------------------------------------------------

    combined_overall_summary.to_csv(
        OUTPUT_DIR
        / "ALL_structural_summary.csv",
        index=False,
    )

    combined_state_summary.to_csv(
        OUTPUT_DIR
        / "ALL_coordination_state_summary.csv",
        index=False,
    )

    combined_coordination_distribution.to_csv(
        OUTPUT_DIR
        / "ALL_coordination_distributions.csv",
        index=False,
    )

    combined_joint_coordination.to_csv(
        OUTPUT_DIR
        / "ALL_joint_peo_tfsi_coordination.csv",
        index=False,
    )

    combined_denticity.to_csv(
        OUTPUT_DIR
        / "ALL_tfsi_denticity.csv",
        index=False,
    )

    combined_tfsi_bridging.to_csv(
        OUTPUT_DIR
        / "ALL_tfsi_metals_per_anion.csv",
        index=False,
    )

    combined_peo_occupancy.to_csv(
        OUTPUT_DIR
        / "ALL_peo_metals_per_chain.csv",
        index=False,
    )

    combined_peo_separation.to_csv(
        OUTPUT_DIR
        / "ALL_peo_eo_separation.csv",
        index=False,
    )

    combined_cluster_distribution.to_csv(
        OUTPUT_DIR
        / "ALL_cluster_size_distributions.csv",
        index=False,
    )

    combined_block_means.to_csv(
        OUTPUT_DIR
        / "ALL_block_means.csv",
        index=False,
    )

    # --------------------------------------------------------
    # Combined manuscript plots
    # --------------------------------------------------------

    make_combined_state_plot(
        combined_state_summary
    )

    make_combined_metric_plot(
        combined_overall_summary,
        metric="mean_peo_oxygen_cn",
        ylabel="Mean PEO oxygen coordination number",
        filename="combined_peo_oxygen_cn",
    )

    make_combined_metric_plot(
        combined_overall_summary,
        metric="mean_tfsi_molecular_cn",
        ylabel="Mean number of TFSI molecules per metal",
        filename="combined_tfsi_molecular_cn",
    )

    make_combined_metric_plot(
        combined_overall_summary,
        metric="fraction_metals_tfsi_bridged",
        ylabel="Fraction of metals in TFSI bridges",
        filename="combined_tfsi_bridging",
    )

    make_combined_metric_plot(
        combined_overall_summary,
        metric="fraction_metals_shared_peo_chain",
        ylabel="Fraction of metals sharing a PEO chain",
        filename="combined_peo_chain_sharing",
    )

    make_combined_metric_plot(
        combined_overall_summary,
        metric="fraction_metals_local_peo_bridged",
        ylabel="Fraction of metals in local PEO bridges",
        filename="combined_local_peo_bridging",
    )

    make_combined_metric_plot(
        combined_overall_summary,
        metric="fraction_metals_in_multi_metal_clusters",
        ylabel="Fraction of metals in multi-metal clusters",
        filename="combined_multi_metal_cluster_fraction",
    )

    make_combined_metric_plot(
        combined_overall_summary,
        metric="mean_cluster_metals_weight_average",
        ylabel="Metal-weighted mean cluster size",
        filename="combined_weight_average_cluster_size",
    )

    print("\n" + "=" * 78)
    print("STRUCTURAL SUMMARY COMPLETED")
    print("=" * 78)

    print(
        f"Results saved in:\n{OUTPUT_DIR.resolve()}"
    )


if __name__ == "__main__":
    main()