# -*- coding: utf-8 -*-
"""
Created on Sun Jul 12 16:16:19 2026

@author: Ajay R. Dwivedi
"""


"""
Structural summary analysis for generic metal-ion polymer electrolytes.

Reads the master coordination databases generated by:

    01_build_master_coordination_database.py

Produces:
    1. Block-averaged structural metrics
    2. Overall structural summary
    3. Coordination-state populations
    4. Coordination-number distributions
    5. Joint PEO-TFSI coordination distributions
    6. TFSI denticity distributions
    7. PEO-chain-sharing and bridging distributions
    8. Metal-TFSI cluster-size distributions
    9. Manuscript-ready plots

Author: Ajay Dwivedi
"""

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# ============================================================
# USER SETTINGS
# ============================================================

SYSTEMS = {
    "example_system": {
        "metal": "metal",
        "composition": "composition",
        "master_file": "coordination_database/example_system/master_coordination_example_system.csv.gz",
        "frame_file": "coordination_database/example_system/frame_summary_example_system.csv",
        "tfsi_bridging_file": "coordination_database/example_system/tfsi_bridging_example_system.csv.gz",
        "peo_bridging_file": "coordination_database/example_system/peo_chain_bridging_example_system.csv.gz",
        "cluster_file": "coordination_database/example_system/cluster_summary_example_system.csv.gz",
    },
}


# Order in which compositions appear in plots.
#
# Replace these labels with your actual four compositions.
COMPOSITION_ORDER = [
    "20_5",
    "10_10",
    "5_15",
    "5_20",
]

# Number of trajectory blocks used for uncertainty estimates.
N_BLOCKS = 5

OUTPUT_DIR = Path("structural_summary")

# Plot settings.
FIGURE_DPI = 300
SAVE_PDF = True

# Remove an initial trajectory portion if needed.
#
# Set to 0.0 to use the complete analyzed trajectory.
DISCARD_INITIAL_FRACTION = 0.0


# ============================================================
# COLUMN TYPES
# ============================================================

MASTER_STRING_COLUMNS = [
    "peo_oxygen_atom_ids",
    "peo_chain_resids",
    "peo_local_eo_indices",
    "peo_chain_eo_mapping",
    "tfsi_oxygen_atom_ids",
    "tfsi_resids",
    "tfsi_denticity",
    "bridging_tfsi_resids",
    "shared_peo_chain_resids",
    "local_peo_bridge_chain_resids",
    "remote_peo_shared_chain_resids",
    "cluster_id",
]


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def ensure_file_exists(path_string):
    """Raise a clear error if an input file is missing."""

    path = Path(path_string)

    if not path.exists():
        raise FileNotFoundError(
            f"Required input file not found:\n{path.resolve()}"
        )

    return path


def read_master_database(path_string):
    """Read the master database without mixed-type warnings."""

    path = ensure_file_exists(path_string)

    dtype_map = {
        column: "string"
        for column in MASTER_STRING_COLUMNS
    }

    return pd.read_csv(
        path,
        dtype=dtype_map,
        low_memory=False,
    )


def read_table(path_string):
    """Read a CSV or compressed CSV."""

    path = ensure_file_exists(path_string)

    return pd.read_csv(
        path,
        low_memory=False,
    )


def discard_initial_frames(dataframe, fraction):
    """
    Remove an initial fraction of frames.

    The cutoff is based on unique frame numbers.
    """

    if fraction <= 0:
        return dataframe.copy()

    if fraction >= 1:
        raise ValueError(
            "DISCARD_INITIAL_FRACTION must be less than 1."
        )

    unique_frames = np.sort(
        dataframe["frame"].unique()
    )

    n_discard = int(
        np.floor(
            len(unique_frames) * fraction
        )
    )

    retained_frames = set(
        unique_frames[n_discard:]
    )

    return dataframe[
        dataframe["frame"].isin(retained_frames)
    ].copy()


def assign_frame_blocks(dataframe, n_blocks):
    """
    Assign unique trajectory frames to approximately equal blocks.

    This avoids splitting rows from the same frame across blocks.
    """

    result = dataframe.copy()

    unique_frames = np.sort(
        result["frame"].unique()
    )

    if len(unique_frames) < n_blocks:
        raise ValueError(
            f"Only {len(unique_frames)} frames are available, "
            f"but N_BLOCKS={n_blocks}."
        )

    frame_groups = np.array_split(
        unique_frames,
        n_blocks,
    )

    frame_to_block = {}

    for block_index, frame_group in enumerate(
        frame_groups,
        start=1,
    ):
        for frame in frame_group:
            frame_to_block[int(frame)] = block_index

    result["block"] = (
        result["frame"]
        .map(frame_to_block)
        .astype(int)
    )

    return result


def block_statistics(block_table, value_columns):
    """
    Calculate mean, standard deviation, and standard error
    across block averages.
    """

    rows = []

    for column in value_columns:
        values = (
            block_table[column]
            .dropna()
            .astype(float)
        )

        n = len(values)

        mean_value = values.mean()

        std_value = (
            values.std(ddof=1)
            if n > 1
            else np.nan
        )

        sem_value = (
            std_value / np.sqrt(n)
            if n > 1
            else np.nan
        )

        rows.append({
            "metric": column,
            "mean": mean_value,
            "block_std": std_value,
            "block_sem": sem_value,
            "n_blocks": n,
        })

    return pd.DataFrame(rows)


def parse_denticity_json(value):
    """
    Parse a tfsi_denticity JSON entry.

    Example:
        '{"41":1,"43":2}'
    becomes:
        [1, 2]
    """

    if pd.isna(value):
        return []

    text = str(value).strip()

    if text in ("", "{}", "<NA>"):
        return []

    try:
        mapping = json.loads(text)
    except json.JSONDecodeError:
        return []

    return [
        int(denticity)
        for denticity in mapping.values()
    ]


def safe_probability_table(series, value_name):
    """Return count and probability for a categorical variable."""

    counts = (
        series
        .value_counts(dropna=False)
        .sort_index()
    )

    total = counts.sum()

    table = counts.rename("count").reset_index()

    table.columns = [
        value_name,
        "count",
    ]

    table["probability"] = (
        table["count"] / total
        if total > 0
        else 0.0
    )

    return table


def save_figure(fig, filename_stem):
    """Save a figure as PNG and optionally PDF."""

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    fig.savefig(
        OUTPUT_DIR / f"{filename_stem}.png",
        dpi=FIGURE_DPI,
        bbox_inches="tight",
    )

    if SAVE_PDF:
        fig.savefig(
            OUTPUT_DIR / f"{filename_stem}.pdf",
            bbox_inches="tight",
        )

    plt.close(fig)


def sort_compositions(dataframe):
    """Apply a consistent composition order."""

    result = dataframe.copy()

    known_order = [
        value
        for value in COMPOSITION_ORDER
        if value in result["composition"].unique()
    ]

    remaining = [
        value
        for value in result["composition"].unique()
        if value not in known_order
    ]

    complete_order = known_order + sorted(remaining)

    result["composition"] = pd.Categorical(
        result["composition"],
        categories=complete_order,
        ordered=True,
    )

    return result.sort_values(
        ["metal_species", "composition"]
    )


# ============================================================
# SYSTEM-LEVEL ANALYSIS
# ============================================================

def analyze_system(system_name, config):
    """Analyze one master structural database."""

    print("\n" + "=" * 78)
    print(f"Analyzing structural database: {system_name}")
    print("=" * 78)

    master = read_master_database(
        config["master_file"]
    )

    frames = read_table(
        config["frame_file"]
    )

    tfsi_bridging = read_table(
        config["tfsi_bridging_file"]
    )

    peo_bridging = read_table(
        config["peo_bridging_file"]
    )

    clusters = read_table(
        config["cluster_file"]
    )

    master = discard_initial_frames(
        master,
        DISCARD_INITIAL_FRACTION,
    )

    frames = discard_initial_frames(
        frames,
        DISCARD_INITIAL_FRACTION,
    )

    tfsi_bridging = discard_initial_frames(
        tfsi_bridging,
        DISCARD_INITIAL_FRACTION,
    )

    peo_bridging = discard_initial_frames(
        peo_bridging,
        DISCARD_INITIAL_FRACTION,
    )

    clusters = discard_initial_frames(
        clusters,
        DISCARD_INITIAL_FRACTION,
    )

    master = assign_frame_blocks(
        master,
        N_BLOCKS,
    )

    frames = assign_frame_blocks(
        frames,
        N_BLOCKS,
    )

    tfsi_bridging = assign_frame_blocks(
        tfsi_bridging,
        N_BLOCKS,
    )

    peo_bridging = assign_frame_blocks(
        peo_bridging,
        N_BLOCKS,
    )

    clusters = assign_frame_blocks(
        clusters,
        N_BLOCKS,
    )

    metal = config["metal"]
    composition = config["composition"]

    system_output_dir = OUTPUT_DIR / system_name

    system_output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ========================================================
    # 1. FRAME-LEVEL BLOCK AVERAGES
    # ========================================================

    structural_columns = [
        "frac_P",
        "frac_PT",
        "frac_T",
        "frac_F",

        "mean_peo_oxygen_cn",
        "mean_peo_chain_cn",
        "mean_tfsi_oxygen_cn",
        "mean_tfsi_molecular_cn",
        "mean_total_oxygen_cn",

        "fraction_coordinated_tfsi_bridging",
        "fraction_all_tfsi_bridging",
        "fraction_metals_tfsi_bridged",

        "fraction_coordinating_peo_chains_shared",
        "fraction_all_peo_chains_shared",
        "fraction_coordinating_peo_chains_local_bridging",
        "fraction_all_peo_chains_local_bridging",

        "fraction_metals_shared_peo_chain",
        "fraction_metals_local_peo_bridged",
        "fraction_metals_remote_peo_shared",

        "mean_metals_per_coordinating_peo_chain",
        "max_metals_on_one_peo_chain",

        "fraction_metals_any_bridge",
        "fraction_metals_both_peo_tfsi_bridged",
        "fraction_metals_peo_only_bridged",
        "fraction_metals_tfsi_only_bridged",

        "mean_cluster_metals_number_average",
        "mean_cluster_metals_weight_average",
        "largest_cluster_n_metals",
        "largest_cluster_metal_fraction",
        "fraction_metals_in_multi_metal_clusters",
        "fraction_single_metal_clusters",
    ]

    available_structural_columns = [
        column
        for column in structural_columns
        if column in frames.columns
    ]

    missing_columns = sorted(
        set(structural_columns)
        - set(available_structural_columns)
    )

    if missing_columns:
        print(
            "\nWarning: the following frame-summary columns "
            "were not found:"
        )

        for column in missing_columns:
            print(f"  - {column}")

    block_frame_means = (
        frames
        .groupby("block", as_index=False)[
            available_structural_columns
        ]
        .mean()
    )

    block_frame_means.insert(
        0,
        "composition",
        composition,
    )

    block_frame_means.insert(
        0,
        "metal_species",
        metal,
    )

    block_frame_means.insert(
        0,
        "system",
        system_name,
    )

    block_frame_means.to_csv(
        system_output_dir
        / f"block_means_{system_name}.csv",
        index=False,
    )

    overall_summary = block_statistics(
        block_frame_means,
        available_structural_columns,
    )

    overall_summary.insert(
        0,
        "composition",
        composition,
    )

    overall_summary.insert(
        0,
        "metal_species",
        metal,
    )

    overall_summary.insert(
        0,
        "system",
        system_name,
    )

    overall_summary.to_csv(
        system_output_dir
        / f"overall_summary_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 2. COORDINATION STATE POPULATIONS
    # ========================================================

    state_order = [
        "P",
        "PT",
        "T",
        "F",
    ]

    state_block = (
        master
        .groupby(
            ["block", "coordination_state"]
        )
        .size()
        .rename("count")
        .reset_index()
    )

    state_totals = (
        state_block
        .groupby("block")["count"]
        .transform("sum")
    )

    state_block["fraction"] = (
        state_block["count"]
        / state_totals
    )

    state_block = (
        state_block
        .pivot(
            index="block",
            columns="coordination_state",
            values="fraction",
        )
        .fillna(0.0)
        .reindex(
            columns=state_order,
            fill_value=0.0,
        )
        .reset_index()
    )

    state_block.insert(
        0,
        "composition",
        composition,
    )

    state_block.insert(
        0,
        "metal_species",
        metal,
    )

    state_block.insert(
        0,
        "system",
        system_name,
    )

    state_block.to_csv(
        system_output_dir
        / f"state_block_fractions_{system_name}.csv",
        index=False,
    )

    state_summary_rows = []

    for state in state_order:
        values = state_block[state]

        state_summary_rows.append({
            "system": system_name,
            "metal_species": metal,
            "composition": composition,
            "state": state,
            "mean_fraction": values.mean(),
            "block_std": values.std(ddof=1),
            "block_sem": (
                values.std(ddof=1)
                / np.sqrt(len(values))
            ),
        })

    state_summary = pd.DataFrame(
        state_summary_rows
    )

    state_summary.to_csv(
        system_output_dir
        / f"state_summary_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 3. COORDINATION-NUMBER DISTRIBUTIONS
    # ========================================================

    coordination_columns = [
        "n_peo_oxygen",
        "n_peo_chains",
        "n_tfsi_oxygen",
        "n_tfsi_molecules",
        "total_oxygen_cn",
    ]

    coordination_distributions = []

    for column in coordination_columns:

        table = safe_probability_table(
            master[column],
            "coordination_number",
        )

        table.insert(
            0,
            "metric",
            column,
        )

        table.insert(
            0,
            "composition",
            composition,
        )

        table.insert(
            0,
            "metal_species",
            metal,
        )

        table.insert(
            0,
            "system",
            system_name,
        )

        coordination_distributions.append(
            table
        )

    coordination_distribution = pd.concat(
        coordination_distributions,
        ignore_index=True,
    )

    coordination_distribution.to_csv(
        system_output_dir
        / f"coordination_distributions_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 4. JOINT PEO-TFSI COORDINATION MAP
    # ========================================================

    joint_counts = (
        master
        .groupby(
            [
                "n_peo_oxygen",
                "n_tfsi_molecules",
            ]
        )
        .size()
        .rename("count")
        .reset_index()
    )

    joint_counts["probability"] = (
        joint_counts["count"]
        / joint_counts["count"].sum()
    )

    joint_counts.insert(
        0,
        "composition",
        composition,
    )

    joint_counts.insert(
        0,
        "metal_species",
        metal,
    )

    joint_counts.insert(
        0,
        "system",
        system_name,
    )

    joint_counts.to_csv(
        system_output_dir
        / f"joint_peo_tfsi_coordination_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 5. TFSI DENTICITY DISTRIBUTION
    # ========================================================

    denticity_values = []

    for value in master["tfsi_denticity"]:
        denticity_values.extend(
            parse_denticity_json(value)
        )

    if denticity_values:
        denticity_distribution = (
            safe_probability_table(
                pd.Series(denticity_values),
                "denticity",
            )
        )
    else:
        denticity_distribution = pd.DataFrame(
            columns=[
                "denticity",
                "count",
                "probability",
            ]
        )

    denticity_distribution.insert(
        0,
        "composition",
        composition,
    )

    denticity_distribution.insert(
        0,
        "metal_species",
        metal,
    )

    denticity_distribution.insert(
        0,
        "system",
        system_name,
    )

    denticity_distribution.to_csv(
        system_output_dir
        / f"tfsi_denticity_distribution_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 6. TFSI BRIDGING DISTRIBUTION
    # ========================================================

    tfsi_metal_count_distribution = (
        safe_probability_table(
            tfsi_bridging["n_coordinating_metals"],
            "n_coordinating_metals",
        )
    )

    tfsi_metal_count_distribution.insert(
        0,
        "composition",
        composition,
    )

    tfsi_metal_count_distribution.insert(
        0,
        "metal_species",
        metal,
    )

    tfsi_metal_count_distribution.insert(
        0,
        "system",
        system_name,
    )

    tfsi_metal_count_distribution.to_csv(
        system_output_dir
        / f"tfsi_metals_per_anion_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 7. PEO CHAIN OCCUPANCY AND BRIDGING
    # ========================================================

    peo_metals_per_chain_distribution = (
        safe_probability_table(
            peo_bridging["n_coordinating_metals"],
            "n_coordinating_metals",
        )
    )

    peo_metals_per_chain_distribution.insert(
        0,
        "composition",
        composition,
    )

    peo_metals_per_chain_distribution.insert(
        0,
        "metal_species",
        metal,
    )

    peo_metals_per_chain_distribution.insert(
        0,
        "system",
        system_name,
    )

    peo_metals_per_chain_distribution.to_csv(
        system_output_dir
        / f"peo_metals_per_chain_{system_name}.csv",
        index=False,
    )

    shared_peo_pairs = peo_bridging[
        peo_bridging["n_metal_pairs"] > 0
    ].copy()

    if len(shared_peo_pairs) > 0:

        separation_distribution = (
            shared_peo_pairs[
                "minimum_pair_eo_separation"
            ]
            .dropna()
            .astype(int)
        )

        separation_distribution = (
            safe_probability_table(
                separation_distribution,
                "minimum_eo_separation",
            )
        )

    else:
        separation_distribution = pd.DataFrame(
            columns=[
                "minimum_eo_separation",
                "count",
                "probability",
            ]
        )

    separation_distribution.insert(
        0,
        "composition",
        composition,
    )

    separation_distribution.insert(
        0,
        "metal_species",
        metal,
    )

    separation_distribution.insert(
        0,
        "system",
        system_name,
    )

    separation_distribution.to_csv(
        system_output_dir
        / f"peo_minimum_eo_separation_{system_name}.csv",
        index=False,
    )

    # ========================================================
    # 8. CLUSTER-SIZE DISTRIBUTIONS
    # ========================================================

    cluster_number_distribution = (
        clusters
        .groupby("n_metals")
        .size()
        .rename("cluster_count")
        .reset_index()
        .sort_values("n_metals")
    )

    cluster_number_distribution[
        "cluster_probability"
    ] = (
        cluster_number_distribution["cluster_count"]
        / cluster_number_distribution[
            "cluster_count"
        ].sum()
    )

    cluster_number_distribution[
        "metal_weight"
    ] = (
        cluster_number_distribution["n_metals"]
        * cluster_number_distribution["cluster_count"]
    )

    cluster_number_distribution[
        "metal_fraction"
    ] = (